// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsNPOr42NMDcc4eBwVtXyGJkrTAMcyZKw',
    appId: '1:785302734592:web:3256138745220dc79955e5',
    messagingSenderId: '785302734592',
    projectId: 'bhojansathi-7873d',
    authDomain: 'bhojansathi-7873d.firebaseapp.com',
    storageBucket: 'bhojansathi-7873d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPxMOpWgJ9wZgb-pwN7Lr_HR_CJeB_6B0',
    appId: '1:785302734592:android:279e61d010dca7819955e5',
    messagingSenderId: '785302734592',
    projectId: 'bhojansathi-7873d',
    storageBucket: 'bhojansathi-7873d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMoy9UA_y6Dh3VkMdL84-cP_MpWNxg9y0',
    appId: '1:785302734592:ios:72e1fe3ebf62baf09955e5',
    messagingSenderId: '785302734592',
    projectId: 'bhojansathi-7873d',
    storageBucket: 'bhojansathi-7873d.appspot.com',
    iosBundleId: 'com.example.bhojansathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMoy9UA_y6Dh3VkMdL84-cP_MpWNxg9y0',
    appId: '1:785302734592:ios:a859300d6410c22b9955e5',
    messagingSenderId: '785302734592',
    projectId: 'bhojansathi-7873d',
    storageBucket: 'bhojansathi-7873d.appspot.com',
    iosBundleId: 'com.example.bhojansathi.RunnerTests',
  );
}
